### ISSUE TITLE
Groovy script execution error

### ISSUE THREAD

**Issue by Saikrsnas** [Alfresco/adf-examples#1] opened 2017-06-08 15:18 UTC
Hi, I have setup insurance-policy-and-claim-center-app as per the instructions provide in the project. When I am trying to create a new policy, Activiti server is throwing groovy script error. PFA the error log of the same. Please suggest if I am missing any configurations.
Thanks,
Saikrishna
[error.txt](https://github.com/Alfresco/adf-examples/files/1061462/error.txt)

**Comment by cijujoseph** [comment] 2017-06-09 13:58
You will have to configure the following properties to false in your activiti-app.properties file. Script tasks come disabled by default in the product.
validator.editor.bpmn.disable.scripttask=false
validator.editor.bpmn.disable.scripttask.groovy=false

**Comment by cijujoseph** [comment] 2017-06-09 14:49
I also updated the readme with a new step (Step 3)

**Comment by Saikrsnas** [comment] 2017-06-13 13:19
I have configured the properties that you have specified. I have even repeated the same steps with a fresh installation. But still the issue is not resolved. Please find attached my installations activiti-app.properties (from %APS-HOME%\tomcat\lib) and error log files. Let me know if I need any additional steps to be configured.
Note: I have installed APS 1.6.2 on Windows OS.

[error_1.txt](https://github.com/Alfresco/adf-examples/files/1071477/error_1.txt)
[activiti-app.properties.txt](https://github.com/Alfresco/adf-examples/files/1071485/activiti-app.properties.txt)

**Comment by cijujoseph** [comment] 2017-06-16 23:05
Updated section 3 of README with the following
Also, please ensure that groovy and javascript are uncommented in the file named whitelisted-scripts.conf in classes/activiti folder

Since you confirmed it is now working, closing the issue

**Closed by cijujoseph** 2017-06-16 23:05 UTC
Labels: question
