### ISSUE TITLE
IE 11 DocumentListComponent issue

### ISSUE THREAD

**Issue by jbabuc** [Alfresco/adf-examples#24] opened 2018-06-27 19:52 UTC
Hi,

In IE 11 when I double click on node in Document List I get "ERROR TypeError: Object doesn't support this action". Works good in chrome. Please suggest a resolution. 

Thanks.

**Comment by fcorti** [comment] 2020-10-28 15:13
Please provide the following info:
1. Description of the context (versions, environment, etc.)
2. Step by step description to reproduce the issue
3. Experienced behaviour
4. Expected behaviour.

Closing the issue because can not reproduce it.
Please reopen it, once you have the requested info.

Thanks.

**Closed as completed by fcorti** 2020-10-28 15:13 UTC
